name: flutter_embed_unity_platform_interface
description: A common platform interface for the flutter_embed_unity plugin.
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 1.0.0
homepage: https://learntoflutter.com
repository: https://github.com/learntoflutter/flutter_embed_unity/tree/main/flutter_embed_unity_platform_interface
issue_tracker: https://github.com/learntoflutter/flutter_embed_unity/issues
documentation: https://github.com/learntoflutter/flutter_embed_unity/wiki
funding:
  - https://www.buymeacoffee.com/pPDtNs6A6T
topics:
  - unity

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6
